spring:
  application:
    name: aiagent
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json
  datasource:
    url: jdbc:postgresql://rm-cn-m414f6wmt0003wwo.rwlb.rds.aliyuncs.com/aiagentdb
    username: aiagent
    password: ${AIAGENT_POSTGRE_PASSWORD}
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yuyue.aiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# searchApi
search-api:
  api-key: ${AIAGENT_SEARCH_API_KEY}
